package _final;

/**
* _final/CalcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, March 16, 2016 10:42:44 AM PDT
*/

public final class CalcHolder implements org.omg.CORBA.portable.Streamable
{
  public _final.Calc value = null;

  public CalcHolder ()
  {
  }

  public CalcHolder (_final.Calc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _final.CalcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _final.CalcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return _final.CalcHelper.type ();
  }

}
