package _final;


/**
* _final/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, March 16, 2016 10:42:44 AM PDT
*/

public interface CalcOperations 
{
  int calculate (String opcode, int op1, int op2);
  int exit ();
} // interface CalcOperations
